apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Base64 encoded values (echo -n 'value' | base64)
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: c2FsbWExMjM=  # salma123
  POSTGRES_DB: YXBwZGJfZGV2b3Bz  # appdb_devops
